version: "3.8"

services:
    nginx:
        container_name: nginx
        image: nginx:alpine
        ports:
            - 80:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - service-1

    service-1:
        container_name: "service-1"
        image: mfroy/service-1
        build: service_1
        environment:
            DATABASE_URI:

    service-2:
        container_name: "service-2"
        image: mfroy/service-2
        build: service_2
        deploy:
            replicas: 4


    service-3:
        container_name: "service-3"
        image: mfroy/service-3
        build: service_3
        deploy:
            replicas: 4


    service-4:
        container_name: "service-4"
        image: mfroy/service-4
        build: service_4
        deploy:
            replicas: 4

            

        

